version: '3.8'

services:
  liveapp:
    image: liveapp
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
      - "8000:8000/udp"
      - "10080:10080/udp"
    tty: true
    stdin_open: true
    restart: always